apiVersion: platform.darede.io/v1alpha1
kind: Aurora
metadata:
  name: mandrade2-db
  namespace: mandrade2
  labels:
    db.engine: aurora-postgresql
spec:
  compositionSelector:
    matchLabels:
      db.engine: aurora-postgresql
  appName: mandrade2
  dbSize: M  # S | M | L
  dbEngine: aurora-postgresql  # aurora-postgresql | aurora-mysql | postgresql | mysql
  engineVersion: "16.11"
  
  # VPC Configuration (auto-populated from platform-params ConfigMap)
  vpcId: "vpc-0a66641a80c762baa"
  
  # Private subnet IDs for Aurora subnet group (must be in different AZs)
  # Auto-populated from EKS cluster VPC configuration
  subnetIds:
    - "subnet-0e482760d4e4f0250"
    - "subnet-001f264a2c946e35c"
    - "subnet-05916f1c5cb54a6a8"
  
  # Security group that will be allowed to connect to Aurora on port 5432
  # Using EKS node security group for direct pod-to-DB connectivity
  allowedSecurityGroupId: "sg-0af4edc484e912aa3"
  
  # Master password secret reference (must exist before creating Aurora)
  masterPasswordSecretRef:
    name: mandrade2-aurora-master-password
    namespace: mandrade2
    key: password
