apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mandrade2-db
  namespace: mandrade2
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: crossplane-connection-secrets
  target:
    name: mandrade2-db
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DB_ENGINE: "aurora-postgresql"
        DB_HOST: "{{ .endpoint }}"
        DB_PORT: "{{ .port }}"
        DB_USER: "{{ .master_username }}"
        DB_PASSWORD: "{{ index . \"attribute.master_password\" }}"
        DB_NAME: "mandrade2"
  dataFrom:
    - find:
        name:
          regexp: ".*-aurora-conn$"
